DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS TEAM;
DROP TABLE IF EXISTS STATE;
DROP TABLE IF EXISTS COLOR;


CREATE TABLE PLAYER (
    PLAYER_ID SERIAL PRIMARY KEY,
    TEAM_ID INT,
    UNIFORM_NUM INT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    MPG INT,
    PPG INT,
    RPG INT,
    APG INT,
    SPG DOUBLE PRECISION,
    BPG DOUBLE PRECISION
);

CREATE TABLE TEAM (
    TEAM_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    STATE_ID INT,
    COLOR_ID INT,
    WINS INT,
    LOSSES INT
);

CREATE TABLE STATE(
    STATE_ID SERIAL,
    NAME VARCHAR(255)
);

CREATE TABLE COLOR(
    COLOR_ID SERIAL,
    NAME VARCHAR(255)
);